"""empty message

Revision ID: 1d84858910e6
Revises: f7f9e78024cd
Create Date: 2019-02-06 18:45:24.956612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d84858910e6'
down_revision = 'f7f9e78024cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
