FROM node:11.6.0-alpine

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install react-scripts@2.1.3 -g

ARG NODE_PATH
ENV NODE_PATH $NODE_PATH

COPY . /usr/src/app

CMD ["npm", "start"]